export const swedish = {
  about: [
    "Välkommen! Jag är en programmerare med passion för en fantastisk webb, här kan ni läsa lite om vem jag är och vad jag gjort i livet hittills!",
    "Jag skulle beskriva mig själv som en positiv optimist, som är lätt att ha att göra med. Det har jag även fått höra av tidigare arbetsgivare och kollegor. Jag arbetar bra självständigt men finner lätt min plats i en grupp.",
    "Sedan vi fick vår första dator så har jag varit en gamer, ett intresse som har följt mig hela livet. Det är också datorspelen som senare skapade mitt intresse för datorer och programmering.",
    'Jag älskar att "nörda ner mig" i ämnen som jag brinner för, till min sambos stora förtjusning... Ett exempel på det är när jag började brygga mitt eget öl för några år sedan. Jag satt i timmar och läste böcker och artiklar om malt/humle/jäst och bryggtekniker.',
    "Ett intresse för färg och form har alltid funnits med mig och jag har alltid målat och designat saker. Bra design fascinerar mig och jag gillar att tänka ut nya lösninger kring funktionalitet.",
    "Mitt estetiska intresse har påverkat de val jag gjort i livet. Jag har spelat gitarr sedan jag var liten, och gick en musiklinje under min gymnasietid. Numera är musiken en hobby och jag spelar ibland ute med bandet Soapmakers.",
    "Några år efter gymnasiet började jag studer keramisk hantverksteknik. Keramiken har betytt mycket för mig och gett utlopp för många av mina kreativa ideer. Jag har en liten keramikstudio i en lada, vid familjens stuga, på landet.",
    "Jag är en naturmänniska. Vi har alltid spenderat mycket tid i skog och mark, med allt ifrån svampplockning till fjällvandringar. Det är i naturen jag hittar min ro och inspiration.",
  ],
  experience: [
    {
      titel: "Frontend utvecklare",
      organization: "Purple Scout",
      location: "Göteborg",
      dateFrom: "dec-2019",
      dateTo: "mar-2020",
      text: [
        "Arbetade i ett agilt team som levererade en webbapp åt ett telecombolag.",
        "Jag byggde frontend komponenter i React, och hanterade backend logik i Node.",
        "Vi arbetade i två veckors sprintar med högt tempo och nära samarbete med kunden.",
      ],
      woe: "w",
      relevance: "1",
    },
    {
      titel: "Systemutvecklare",
      organization: "Iver/Candidator",
      location: "Alingsås",
      dateFrom: "jun-2018",
      dateTo: "dec-2019",
      text: [
        "Som systemutvecklare på Iver arbetar jag i C# och utvecklar deras system som används båda av Iver och deras kunder.",
        "Det är ett stort system som hanterar allt från transport till ekonomi till tidrapportering.",
        "Det dagliga arbetet består av att bygga och implementera ny funktionalitet, eller att justera befintlig funktionalitet utefter hur kunderna vill ha det.",
        "Tempot var högt och vi släppte nya releaser nästan dagligen.",
      ],
      woe: "w",
      relevance: "1",
    },
    {
      titel: "Javautvecklare",
      organization: "Jensen yrkeshögskola",
      location: "Göteborg",
      dateFrom: "sep-2016",
      dateTo: "jun-2018",
      text: [
        "Fullstack utbildning med inrikting Java.",
        "Tekniker som jag arbetat med under studietiden:",
        "J2SE, J2EE, JSF, JSP, JDBC, JPA, Hibernate, JAX-rs, multithreading, Git, SQL, HTML/CSS, JavaScript AJAX, JQuery, Bootstrap, React, OOP Design, TDD, Scrum.",
      ],
      woe: "e",
      relevance: "1",
    },
    {
      titel: "Administratör",
      organization: "HSB Nordvästra Götaland",
      location: "Lidköping/Vänersborg/Skövde",
      dateFrom: "jan-2014",
      dateTo: "aug-2016",
      text: [
        "Mina arbetsuppgifter bestod av hantering av hyror, överlåtelser, andrahandsuthyrningar, medlemsaviseringar och pantbrev för bostadsrätter, hyresavtal för lokaler och parkeringar/garageplatser.",
        "Jag hade daglig kontakt med våra medlemmar, mäklare, och banker. Jag svarade på deras frågor via telefon, mejl och i vår reception.",
      ],
      woe: "w",
      relevance: "2",
    },
    {
      titel: "Keramisk hantverksteknik",
      organization: "Formakademin",
      location: "Lidköping",
      dateFrom: "aug-2011",
      dateTo: "maj-2013",
      text: ["Försjupning innom keramisk hantverksteknik."],
      woe: "e",
      relevance: "2",
    },
    {
      titel: "Keramisk grundutbildning",
      organization: "Grebbestads folkhögskola",
      location: "Grebbestad.",
      dateFrom: "aug-2011",
      dateTo: "maj-2011",
      text: ["Grundläggande keramisk utbidning."],
      woe: "e",
      relevance: "2",
    },
    {
      titel: "Montör",
      organization: "Slangflex",
      location: "Göteborg",
      dateFrom: "okt-2008",
      dateTo: "maj-2010",
      text: [
        "I arbetsuppgifterna ingick vanliga lageruppgifter (rätt sak på rätt plats) och att dagligen ta hand om inkommande och utgående gods.",
        "Därtill ingick försäljning på plats och över telefon, montering av produkter samt leverans av gods inom göteborgsområdet.",
      ],
      woe: "w",
      relevance: "3",
    },
    {
      titel: "Operatör",
      organization: "Postens ODR-Central",
      location: "Göteborg.",
      dateFrom: "aug-2002",
      dateTo: "dec-2007",
      text: [
        "Arbetade på postens oadresseradreklam(ODR)-central Göteborg.",
        "År 2004 fick jag befattning maskinoperatör. Arbetsuppgifterna som maskinoperatör innefattade att justera maskiner och att styra över en personalstyrka på 4-8 personer beroende på bemanning.",
        "Via posten tog jag truckkörkort, för att köra fram gods till maskinen och hjälpa till med att lasta av inkommande gods från lastbilarna.",
      ],
      woe: "w",
      relevance: "3",
    },
    {
      titel: "Estetiska programmet",
      organization: "Hvitfeldska",
      location: "Göteborg",
      dateFrom: "aug-1999",
      dateTo: "jun-2002",
      text: ["Under min gymnasietid studerade jag musik."],
      woe: "e",
      relevance: "3",
    },
  ],
  contact: [
    {
      id: "mail",
      text: "E-post",
      link: "henrik.g.hagstrom@gmail.com",
    },
    {
      id: "twitter",
      text: "Twitter",
      link: "https://twitter.com/hagstrom_henrik",
    },
    {
      id: "linkedin",
      text: "LinkedIn",
      link: "https://www.linkedin.com/in/henrikhagström/",
    },
  ],
};

export const english = {
  about:
    "Engelska !!!!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Velit scelerisque in dictum non consectetur a erat. Vitae elementum curabitur vitae nunc sed velit. Lacus vestibulum sed arcu non odio euismod lacinia. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Montes nascetur ridiculus mus mauris vitae. Placerat in egestas erat imperdiet sed. Elementum eu facilisis sed odio. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Tellus molestie nunc non blandit massa enim. In tellus integer feugiat scelerisque varius morbi. Faucibus turpis in eu mi bibendum. Sed elementum tempus egestas sed sed risus. Morbi blandit cursus risus at ultrices. Volutpat est velit egestas dui id. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. At auctor urna nunc id cursus metus aliquam eleifend. Odio ut enim blandit volutpat maecenas volutpat blandit.",
  experience: [
    {
      titel: "",
      organization: "",
      location: "",
      dateFrom: "",
      dateTo: "",
      text: [],
      woe: "",
      relevance: "",
    },
  ],
  contact: {
    mail: {
      text: "",
      link: "",
    },
    linkedIn: {
      text: "",
      link: "",
    },
    twitter: {
      text: "",
      link: "",
    },
  },
};
